/var/log/nginx/*.log {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 644 nginx nginx
    maxsize 50M
    postrotate
        /usr/sbin/nginx -s reload > /dev/null 2>&1 || true
    endpostrotate
}